### ISSUE TITLE
周二7,8节和周四5,6节课显示不出来

### ISSUE THREAD

**Issue by Airmole** [qq273681448/TimeTable#1]
如图所示：周二7,8节和周四5,6节课显示不出来!也不知道是bug还是我的用法不对[class](https://user-images.githubusercontent.com/20333663/38405703-c1d482c0-39a3-11e8-9232-996805348ba1.jpg)

**Comment by tap6** [comment]
检查出来了，检查了好一会儿，通过审查元素查出来了，字体是白色且background-color值为空，所以会显示不出来，作者colorArrays里只有八个颜色，但是使用了background-color:{{colorArrays[index%9]}}的语句，只需要把9改成8就行了。这行语句在注释下边儿。
